[package]
name = "cairn"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
http-body-util = "0.1.3"
hyper = { version = "1.10.1", features = ["full"] }
hyper-util = { version = "0.1.20", features = ["full"] }
tokio = { version = "1.52.3", features = ["full"] }
tokio-util = "0.7.18"
