[package]
name = "cairn"
version = "0.1.1"
edition = "2024"
license = "Apache-2.0"
authors = ["Justus Zorn"]

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
deadpool-postgres = "0.14.1"
http-body-util = "0.1.3"
md-5 = "0.10.6"
hyper = { version = "1.10.1", features = ["full"] }
hyper-util = { version = "0.1.20", features = ["full"] }
libc = "0.2"
percent-encoding = "2.3.2"
roxmltree = "0.20.0"
tokio = { version = "1.52.3", features = ["full"] }
tokio-postgres = { version = "0.7.17", features = ["with-uuid-1"] }
tokio-util = "0.7.18"
uuid = { version = "1.23.3", features = ["v4"] }
